name: Azure Checker
run-name: ${{ github.actor }} is checking PAN-OS versions on Azure
on:
  workflow_dispatch:
  schedule:
    - cron: "15 */6 * * *"

jobs:
  panos-checker:
    permissions:
      contents: write
    name: "panos-checker"

    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v7"
        with:
          ref: ${{ github.ref_name }}

      - name: Run Azure processing
        run: |-
          pip install -r requirements.txt
          python azure-processing.py
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Commit and Push
        run: |-
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add azure.md data/
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git pull --rebase
          git push
