name: GCP Checker
run-name: ${{ github.actor }} is checking PAN-OS versions on GCP
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  panos-checker:
    name: "panos-checker"

    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v3"
        with:
          ref: ${{ github.head_ref }}

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CREDS }}"

      # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth` task above
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Get GCP PAN-OS base images lists"
        run: |-
          gcloud compute images list --project paloaltonetworksgcp-public --no-standard-images --format="value(NAME)" --filter="name~'vmseries'" > gcp-list.txt

      - name: "Get GCP Panorama base images lists"
        run: |-
          gcloud compute images list --project paloaltonetworksgcp-public --no-standard-images --format="value(NAME)" --filter="name~'panorama'" > gcp-rama-list.txt

      - name: Run GCP post-processing
        run: |-
          python gcp-processing.py gcp-list.txt gcp-rama-list.txt > gcp.md

      - name: Commit
        run: |-
          git config user.name "Jimmy"
          git config user.email "jamesholland-uk@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}          
          git add gcp.md
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0

      - name: Push
        run: |-
          git push
